# POST http://localhost:3000/customers HTTP/1.1
# content-type: application/json

# { 
#     "customer": {
#         "firstName":"Alex",
#         "lastName":"Bedada",
#         "phoneNumber": "251-9217-27-36",
#         "email": "aegon0355@gmail.com" 
#     }
# }
#create

# GET http://localhost:3000/customers HTTP/1.1
#index


# GET http://localhost:3000/customers/1 HTTP/1.1
#show

# PUT http://localhost:3000/customers/1 HTTP/1.1
# content-type: application/json

# { 
#     "customer": {
#         "firstName":"Chala" 
#     }
# }
#update

GET http://localhost:3000/dress_transactions HTTP/1.1




