
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5435
  username: myuser
  password: mypassword
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_development

  
test:
  <<: *default
  database: backend_test


production:
  <<: *default
  database: backend_production
  customername: backend
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
